# Generated by Django 5.0.6 on 2024-06-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
